### ISSUE TITLE
Npm start

### ISSUE THREAD

**Issue by EliseMalard** [adaltas/ece-webtech-2021-fall#26]
Hello, I have an issue with my npm start for the fornt-end: 
( this issue appears randomly, I just have to re start my VM and this error disappears, but sometime I have to re start my VM a couple of time so that it works.)
`Starting the development server...

node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/elise/Documents/Webtech_MALARD_DEDUIT/project/front-end/public'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2247:34)
    at createFsWatchInstance (/home/elise/Documents/Webtech_MALARD_DEDUIT/project/front-end/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:38:15)
    at setFsWatchListener (/home/elise/Documents/Webtech_MALARD_DEDUIT/project/front-end/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/elise/Documents/Webtech_MALARD_DEDUIT/project/front-end/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/elise/Documents/Webtech_MALARD_DEDUIT/project/front-end/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:429:19)
    at FSWatcher.<anonymous> (/home/elise/Documents/Webtech_MALARD_DEDUIT/project/front-end/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:477:19)
    at FSWatcher.<anonymous> (/home/elise/Documents/Webtech_MALARD_DEDUIT/project/front-end/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:482:16)
    at FSReqCallback.oncomplete (node:fs:199:5)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (/home/elise/Documents/Webtech_MALARD_DEDUIT/project/front-end/node_modules/webpack-dev-server/node_modules/chokidar/index.js:260:10)
    at createFsWatchInstance (/home/elise/Documents/Webtech_MALARD_DEDUIT/project/front-end/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:40:5)
    at setFsWatchListener (/home/elise/Documents/Webtech_MALARD_DEDUIT/project/front-end/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    [... lines matching original stack trace ...]
    at FSReqCallback.oncomplete (node:fs:199:5) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/home/elise/Documents/Webtech_MALARD_DEDUIT/project/front-end/public',
  filename: '/home/elise/Documents/Webtech_MALARD_DEDUIT/project/front-end/public'
}
`

**Comment by wdavidw** [comment]
Quick googling: https://www.google.com/search?q=ENOSPC, for example here https://medium.com/@Pavan_/create-react-app-enospc-issue-on-linux-5f946df8479c:

> https://medium.com/@Pavan_/create-react-app-enospc-issue-on-linux-5f946df8479c

The error means there is not enough space on your filesystem, we might be true .. or not as illustrated in the medium article. Check your file system usage but I won't be surprise if the problem comes from having to many open files like in the article. In such case, follow his instructions: `echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`
